#tabspaces = 8

[font]
size = 14.0

[font.normal]
family = "monaco"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002r"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002$"
key = "Comma"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002("
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002;"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002o"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002{"
key = "LBracket"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0002}"
key = "RBracket"
mods = "Command|Control"

[scrolling]
#auto_scroll = true
history = 100000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux attach || tmux new -s personal"]
program = "/usr/local/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 400
lines = 300

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
